# SPDX-FileCopyrightText: 2025 OVHcloud
# SPDX-License-Identifier: Apache-2.0

site_name: OVHcloud TechLabs - Workbooks
site_description: Comprehensive workbooks for OVHcloud TechLabs
site_url: https://cougz.github.io/ovh-techlabs-workbooks

# Repository
repo_name: cougz/ovh-techlabs-workbooks
repo_url: https://github.com/cougz/ovh-techlabs-workbooks

# Copyright
copyright: Copyright &copy; 2025 OVHcloud

extra:
  generator: false
  social:
  - icon: fontawesome/brands/linkedin 
    link: https://www.linkedin.com/company/ovhgroup/


# Configuration
theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.indexes
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.share
  logo: assets/ovhcloud.svg

# Plugins
plugins:
  - search

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cougz/ovh-techlabs-workbooks
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ovhcloud
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ovhcloud/

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Public Cloud:
    - Overview: public-cloud/index.md
    - AI Endpoints:
      - Overview: public-cloud/ai-endpoints/index.md
      - Retrieval Augmented Generation Testing Using VLM:
        - Overview: public-cloud/ai-endpoints/retrieval-augmented-generation-testing-using-vlm/index.md
        - Workbook: public-cloud/ai-endpoints/retrieval-augmented-generation-testing-using-vlm/workbook.md
      - Python LangChain Chatbot:
        - Overview: public-cloud/ai-endpoints/python-langchain-chatbot/index.md
        - Workbook: public-cloud/ai-endpoints/python-langchain-chatbot/workbook.md
      - LLM Fine-Tuning:
        - Overview: public-cloud/ai-endpoints/llm-fine-tuning/index.md
        - Workbook: public-cloud/ai-endpoints/llm-fine-tuning/workbook.md
      - Car Damage Verification Using VLM:
        - Overview: public-cloud/ai-endpoints/car-damage-verification-using-vlm/index.md
        - Workbook: public-cloud/ai-endpoints/car-damage-verification-using-vlm/workbook.md
